drop table if exists member CASCADE;
멤버
create table Member(
    id bigint generated by default as identity,
    email varchar(50) not null,
    nickname varchar(50) not null,
    password varchar(100) not null,
    auth varchar(50) not null,
    regdate timestamp,
    primary key (id),
    UNIQUE KEY memberemail_UNIQUE (email),
    UNIQUE KEY nickname_UNIQUE (nickname)
);
drop table if exists Board CASCADE;
게시판
create table Board(
    id bigint generated by default as identity,
    member_id bigint,
    title varchar(255),
    content clob,
    type varchar(20) not null,
    hit bigint not null,
    recommend bigint not null,
    regdate timestamp,
    primary key (id),
    foreign key (member_id) references Member(id)
);
drop table if exists Player CASCADE;
create table Player(
    id bigint generated by default as identity,
    name varchar(10) not null,
    height int not null,
    weight int not null,
    bodyform varchar(10) not null,
    birthday varchar(20) not null,
    country varchar(50) not null,
    position varchar(10) not null,
    UNIQUE KEY PlayerName_UNIQUE (name),
    primary key (id)
);
drop table if exists Season CASCADE;
create table Season(
    id bigint generated by default as identity,
    name varchar(100) not null,
    file varchar(2500) not null,
    UNIQUE KEY SeasonName_UNIQUE (name),
    primary key (id)
);
drop table if exists datan CASCADE;
create table datan(
    id bigint generated by default as identity,
    season_id bigint not null,
    player_id bigint not null,
    salaryup int not null,
    speed int not null,
    shooting int not null,
    pass int not null,
    dribble int not null,
    defence int not null,
    physical int not null,
    blocking int not null,
    club varchar(10) not null,
    overall int not null,
    img_file varchar(2500) not null,
    primary key (id),
    foreign key (season_id) references Season(id),
    foreign key (player_id) references Player(id)
);
drop table if exists grade CASCADE;
create table grade(
    member_id  bigint not null,
    datan_id  bigint not null,
    score int not null,
    foreign key (member_id) references Member(id),
    foreign key (datan_id) references datan(id)
);
drop table if exists Datan_Comments CASCADE;
create table Datan_Comments(
    id bigint generated by default as identity,
    datan_id  bigint not null,
    member_id bigint not null,
    content varchar(999) not null,
    regdate timestamp,
    modify_regdate timestamp,
    ref bigint,
    step bigint,
    refOrder bigint,
    answerNum bigint,
    parentNum bigint,
    primary key (id),
    foreign key (member_id) references member(id),
    foreign key (datan_id) references datan(id)
);




















역할
create table role(
        id bigint generated by default as identity,
        name varchar(50) not null,
        primary key(id)
);
시큐리티 연결 테이블
create table member_role(
        member_id bigint  not null,
        role_id bigint  not null,
        primary key(member_id, role_id),
        foreign key (member_id) references member(id),
        foreign key (role_id) references role(id)
);